name: To build and serve

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build executables
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build executables
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/rclone-logs-prometheus-metrics-converter-linux-amd64 .

      - name: Release nightly
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: build/rclone-logs-prometheus-metrics-converter-linux-amd64
          fail_on_unmatched_files: true
